### ISSUE TITLE
Not centered when you reach bottom or top the scroll

### ISSUE THREAD

**Issue by Yaco** [ajnsit/center-cursor#1]
Hi!

I think It should add extra empty lines to make it always centered, even when you reach the limits of the scroll. 

Can you add the feature? Thx

**Comment by ajnsit** [comment]
v0.3.0 now supports atom's inbuilt "allow scrolling past the last line" setting (Preferences -> Editor). Check it out.

**Comment by Yaco** [comment]
yeah, great!
